######################## default configuration ####################
baseURL = "https://py-img-gen.github.io"
languageCode = "ja"
title = "Pythonで学ぶ画像生成"
theme = "influencer-hugo"
summaryLength = "10"
paginate = 6

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "https://cdn.jsdelivr.net/npm/line-seed-jp@0.0.5/line-seed-jp.min.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
URL = "https://unpkg.com/budoux/bundle/budoux-ja.min.js"

############################## navigation ###############################
[menu]

[[menu.main]]
name = "概要"
URL = "book"
weight = 1

[[menu.main]]
name = "目次"
URL = "chapter"
weight = 2

# [[menu.main]]
# name = "Reviews"
# URL = "review"
# weight = 3

[[menu.main]]
name = "著者"
URL = "author"
weight = 4

[[menu.main]]
name = "補足"
URL = "blog"
weight = 5

[[menu.main]]
name = "リンク"
URL = "contact"
weight = 6


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = '"Pythonで学ぶ画像生成"のランディングページです。'
author = "北田 俊輔"
# Google Analytics
googleAnalyticsID = "" # Your ID
# copyright
copyright = "Copyright &copy; 2025 [Shunsuke Kitada](https://shunk031.me/). All Rights Reserved"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# Footer ########################
[params.footer]
content = "近年の技術の発展により、画像生成技術はますます身近になっています。本書は、画像生成について実践的に学べるように、Pythonを使った実装を示しています。"


############################# post share ###################
[[params.share]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"
