name: Page Build

on: [push]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .

      - name: Typo check
        uses: crate-ci/typos@v1.29.0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://py-img-gen.github.iuo
          pages_path: ./public
          cmd_params: "\
            --timeout=20 \
            --buffer-size 8192 \
            --max-connections=10 \
            --max-response-body-size=70000000 \
            --ignore-fragments \
            -e t.co \
            -e twitter.com \
            "

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          path: ./public

  deploy:
    needs: build

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifacts
        uses: actions/deploy-pages@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
